/** Built-in free icon packs placeable on the timeline (not project uploads). */

export type IconSetId = 'material' | 'lucide';

export interface IconDef {
  set: IconSetId;
  name: string;
  label: string;
  tags?: string[];
}

export interface IconSetMeta {
  id: IconSetId;
  label: string;
  license: string;
}

export const ICON_SETS: IconSetMeta[] = [
  { id: 'material', label: 'Material Symbols', license: 'Apache 2.0' },
  { id: 'lucide', label: 'Lucide', license: 'ISC' },
];

/** Curated Material Symbols Outlined names (ligature / glyph name). */
const MATERIAL: Omit<IconDef, 'set'>[] = [
  { name: 'favorite', label: 'Favorite', tags: ['heart', 'like'] },
  { name: 'favorite_border', label: 'Favorite outline', tags: ['heart'] },
  { name: 'star', label: 'Star', tags: ['rating'] },
  { name: 'star_border', label: 'Star outline' },
  { name: 'home', label: 'Home' },
  { name: 'search', label: 'Search' },
  { name: 'settings', label: 'Settings', tags: ['gear'] },
  { name: 'person', label: 'Person', tags: ['user', 'profile'] },
  { name: 'group', label: 'Group', tags: ['people', 'users'] },
  { name: 'mail', label: 'Mail', tags: ['email'] },
  { name: 'call', label: 'Call', tags: ['phone'] },
  { name: 'chat', label: 'Chat', tags: ['message'] },
  { name: 'notifications', label: 'Notifications', tags: ['bell'] },
  { name: 'calendar_month', label: 'Calendar' },
  { name: 'schedule', label: 'Schedule', tags: ['clock', 'time'] },
  { name: 'place', label: 'Place', tags: ['location', 'map', 'pin'] },
  { name: 'map', label: 'Map' },
  { name: 'navigation', label: 'Navigation' },
  { name: 'shopping_cart', label: 'Cart', tags: ['shop'] },
  { name: 'shopping_bag', label: 'Bag' },
  { name: 'payments', label: 'Payments', tags: ['money', 'card'] },
  { name: 'credit_card', label: 'Credit card' },
  { name: 'local_offer', label: 'Offer', tags: ['tag', 'deal'] },
  { name: 'sell', label: 'Sell', tags: ['tag'] },
  { name: 'check', label: 'Check', tags: ['ok', 'done'] },
  { name: 'check_circle', label: 'Check circle' },
  { name: 'close', label: 'Close', tags: ['x', 'cancel'] },
  { name: 'add', label: 'Add', tags: ['plus'] },
  { name: 'remove', label: 'Remove', tags: ['minus'] },
  { name: 'edit', label: 'Edit', tags: ['pencil'] },
  { name: 'delete', label: 'Delete', tags: ['trash'] },
  { name: 'share', label: 'Share' },
  { name: 'link', label: 'Link' },
  { name: 'content_copy', label: 'Copy' },
  { name: 'download', label: 'Download' },
  { name: 'upload', label: 'Upload' },
  { name: 'cloud', label: 'Cloud' },
  { name: 'cloud_upload', label: 'Cloud upload' },
  { name: 'photo_camera', label: 'Camera', tags: ['photo'] },
  { name: 'image', label: 'Image', tags: ['photo'] },
  { name: 'videocam', label: 'Video camera' },
  { name: 'movie', label: 'Movie' },
  { name: 'music_note', label: 'Music' },
  { name: 'mic', label: 'Microphone' },
  { name: 'volume_up', label: 'Volume' },
  { name: 'play_arrow', label: 'Play' },
  { name: 'pause', label: 'Pause' },
  { name: 'stop', label: 'Stop' },
  { name: 'skip_next', label: 'Next' },
  { name: 'skip_previous', label: 'Previous' },
  { name: 'replay', label: 'Replay' },
  { name: 'visibility', label: 'Visibility', tags: ['eye'] },
  { name: 'visibility_off', label: 'Hidden' },
  { name: 'lock', label: 'Lock' },
  { name: 'lock_open', label: 'Unlock' },
  { name: 'key', label: 'Key' },
  { name: 'info', label: 'Info' },
  { name: 'help', label: 'Help' },
  { name: 'warning', label: 'Warning' },
  { name: 'error', label: 'Error' },
  { name: 'bolt', label: 'Bolt', tags: ['flash', 'energy'] },
  { name: 'lightbulb', label: 'Lightbulb', tags: ['idea'] },
  { name: 'auto_awesome', label: 'Sparkle', tags: ['ai', 'magic'] },
  { name: 'palette', label: 'Palette', tags: ['art', 'color'] },
  { name: 'brush', label: 'Brush' },
  { name: 'format_paint', label: 'Paint' },
  { name: 'widgets', label: 'Widgets' },
  { name: 'dashboard', label: 'Dashboard' },
  { name: 'analytics', label: 'Analytics', tags: ['chart'] },
  { name: 'trending_up', label: 'Trending up' },
  { name: 'trending_down', label: 'Trending down' },
  { name: 'rocket_launch', label: 'Rocket' },
  { name: 'flight', label: 'Flight', tags: ['plane'] },
  { name: 'directions_car', label: 'Car' },
  { name: 'directions_bike', label: 'Bike' },
  { name: 'restaurant', label: 'Restaurant', tags: ['food'] },
  { name: 'local_cafe', label: 'Cafe', tags: ['coffee'] },
  { name: 'fitness_center', label: 'Fitness', tags: ['gym'] },
  { name: 'spa', label: 'Spa' },
  { name: 'school', label: 'School', tags: ['education'] },
  { name: 'work', label: 'Work', tags: ['briefcase'] },
  { name: 'apartment', label: 'Apartment', tags: ['building'] },
  { name: 'storefront', label: 'Storefront' },
  { name: 'public', label: 'Public', tags: ['globe', 'world'] },
  { name: 'language', label: 'Language' },
  { name: 'wifi', label: 'Wi‑Fi' },
  { name: 'bluetooth', label: 'Bluetooth' },
  { name: 'battery_full', label: 'Battery' },
  { name: 'smartphone', label: 'Smartphone' },
  { name: 'laptop', label: 'Laptop' },
  { name: 'desktop_windows', label: 'Desktop' },
  { name: 'headphones', label: 'Headphones' },
  { name: 'watch', label: 'Watch' },
  { name: 'pets', label: 'Pets' },
  { name: 'eco', label: 'Eco', tags: ['leaf', 'nature'] },
  { name: 'water_drop', label: 'Water' },
  { name: 'wb_sunny', label: 'Sunny', tags: ['sun', 'weather'] },
  { name: 'nightlight', label: 'Night', tags: ['moon'] },
  { name: 'celebration', label: 'Celebration', tags: ['party'] },
  { name: 'cake', label: 'Cake' },
  { name: 'card_giftcard', label: 'Gift' },
  { name: 'thumb_up', label: 'Thumbs up' },
  { name: 'thumb_down', label: 'Thumbs down' },
  { name: 'emoji_events', label: 'Trophy', tags: ['award'] },
  { name: 'military_tech', label: 'Medal' },
  { name: 'verified', label: 'Verified' },
  { name: 'new_releases', label: 'New' },
  { name: 'campaign', label: 'Campaign', tags: ['megaphone', 'ads'] },
  { name: 'handshake', label: 'Handshake' },
  { name: 'volunteer_activism', label: 'Charity', tags: ['donate'] },
  { name: 'health_and_safety', label: 'Health' },
  { name: 'medication', label: 'Medication' },
  { name: 'science', label: 'Science' },
  { name: 'code', label: 'Code' },
  { name: 'terminal', label: 'Terminal' },
  { name: 'database', label: 'Database' },
  { name: 'dns', label: 'DNS', tags: ['server'] },
  { name: 'security', label: 'Security', tags: ['shield'] },
  { name: 'gavel', label: 'Gavel', tags: ['law'] },
  { name: 'balance', label: 'Balance' },
  { name: 'attach_money', label: 'Money', tags: ['dollar'] },
  { name: 'savings', label: 'Savings' },
  { name: 'inventory_2', label: 'Inventory', tags: ['box'] },
  { name: 'local_shipping', label: 'Shipping', tags: ['truck'] },
  { name: 'qr_code_2', label: 'QR code' },
  { name: 'barcode', label: 'Barcode' },
  { name: 'print', label: 'Print' },
  { name: 'bookmark', label: 'Bookmark' },
  { name: 'flag', label: 'Flag' },
  { name: 'push_pin', label: 'Pin' },
  { name: 'filter_alt', label: 'Filter' },
  { name: 'tune', label: 'Tune', tags: ['sliders'] },
  { name: 'grid_view', label: 'Grid' },
  { name: 'view_list', label: 'List' },
  { name: 'menu', label: 'Menu', tags: ['hamburger'] },
  { name: 'more_horiz', label: 'More' },
  { name: 'arrow_forward', label: 'Arrow forward' },
  { name: 'arrow_back', label: 'Arrow back' },
  { name: 'arrow_upward', label: 'Arrow up' },
  { name: 'arrow_downward', label: 'Arrow down' },
  { name: 'north_east', label: 'Arrow northeast' },
  { name: 'refresh', label: 'Refresh' },
  { name: 'sync', label: 'Sync' },
  { name: 'open_in_new', label: 'Open in new' },
  { name: 'fullscreen', label: 'Fullscreen' },
  { name: 'zoom_in', label: 'Zoom in' },
  { name: 'zoom_out', label: 'Zoom out' },
  { name: 'crop_free', label: 'Crop free' },
  { name: 'layers', label: 'Layers' },
  { name: 'texture', label: 'Texture' },
  { name: 'animation', label: 'Animation' },
  { name: 'smart_display', label: 'Smart display' },
  { name: 'live_tv', label: 'Live TV' },
  { name: 'podcasts', label: 'Podcasts' },
  { name: 'newspaper', label: 'Newspaper' },
  { name: 'article', label: 'Article' },
  { name: 'book', label: 'Book' },
  { name: 'menu_book', label: 'Menu book' },
  { name: 'quiz', label: 'Quiz' },
  { name: 'psychology', label: 'Psychology' },
  { name: 'self_improvement', label: 'Self improvement' },
  { name: 'accessibility', label: 'Accessibility' },
  { name: 'child_care', label: 'Child care' },
  { name: 'elderly', label: 'Elderly' },
  { name: 'diversity_3', label: 'Diversity' },
  { name: 'sentiment_satisfied', label: 'Happy', tags: ['smile', 'emoji'] },
  { name: 'sentiment_dissatisfied', label: 'Sad', tags: ['emoji'] },
  { name: 'mood', label: 'Mood', tags: ['emoji'] },
  { name: 'cruelty_free', label: 'Cruelty free' },
  { name: 'recycling', label: 'Recycling' },
  { name: 'energy_savings_leaf', label: 'Energy leaf' },
  { name: 'solar_power', label: 'Solar' },
  { name: 'electric_car', label: 'Electric car' },
  { name: 'ev_station', label: 'EV station' },
];

/** Popular Lucide icons (file name under lucide-static/icons). */
const LUCIDE: Omit<IconDef, 'set'>[] = [
  { name: 'heart', label: 'Heart', tags: ['like', 'love'] },
  { name: 'star', label: 'Star' },
  { name: 'home', label: 'Home' },
  { name: 'search', label: 'Search' },
  { name: 'settings', label: 'Settings', tags: ['gear'] },
  { name: 'user', label: 'User', tags: ['person'] },
  { name: 'users', label: 'Users', tags: ['group'] },
  { name: 'mail', label: 'Mail' },
  { name: 'phone', label: 'Phone' },
  { name: 'message-circle', label: 'Message' },
  { name: 'bell', label: 'Bell' },
  { name: 'calendar', label: 'Calendar' },
  { name: 'clock', label: 'Clock' },
  { name: 'map-pin', label: 'Map pin' },
  { name: 'map', label: 'Map' },
  { name: 'shopping-cart', label: 'Cart' },
  { name: 'shopping-bag', label: 'Bag' },
  { name: 'credit-card', label: 'Credit card' },
  { name: 'tag', label: 'Tag' },
  { name: 'check', label: 'Check' },
  { name: 'check-circle', label: 'Check circle' },
  { name: 'x', label: 'Close', tags: ['cancel'] },
  { name: 'plus', label: 'Plus', tags: ['add'] },
  { name: 'minus', label: 'Minus' },
  { name: 'pencil', label: 'Pencil', tags: ['edit'] },
  { name: 'trash-2', label: 'Trash', tags: ['delete'] },
  { name: 'share-2', label: 'Share' },
  { name: 'link', label: 'Link' },
  { name: 'copy', label: 'Copy' },
  { name: 'download', label: 'Download' },
  { name: 'upload', label: 'Upload' },
  { name: 'cloud', label: 'Cloud' },
  { name: 'camera', label: 'Camera' },
  { name: 'image', label: 'Image' },
  { name: 'video', label: 'Video' },
  { name: 'film', label: 'Film' },
  { name: 'music', label: 'Music' },
  { name: 'mic', label: 'Mic' },
  { name: 'volume-2', label: 'Volume' },
  { name: 'play', label: 'Play' },
  { name: 'pause', label: 'Pause' },
  { name: 'eye', label: 'Eye' },
  { name: 'eye-off', label: 'Eye off' },
  { name: 'lock', label: 'Lock' },
  { name: 'unlock', label: 'Unlock' },
  { name: 'key', label: 'Key' },
  { name: 'info', label: 'Info' },
  { name: 'help-circle', label: 'Help' },
  { name: 'alert-triangle', label: 'Warning' },
  { name: 'zap', label: 'Zap', tags: ['bolt'] },
  { name: 'lightbulb', label: 'Lightbulb' },
  { name: 'sparkles', label: 'Sparkles', tags: ['ai'] },
  { name: 'palette', label: 'Palette' },
  { name: 'brush', label: 'Brush' },
  { name: 'layout-dashboard', label: 'Dashboard' },
  { name: 'bar-chart-3', label: 'Bar chart' },
  { name: 'trending-up', label: 'Trending up' },
  { name: 'rocket', label: 'Rocket' },
  { name: 'plane', label: 'Plane' },
  { name: 'car', label: 'Car' },
  { name: 'bike', label: 'Bike' },
  { name: 'utensils', label: 'Utensils', tags: ['food'] },
  { name: 'coffee', label: 'Coffee' },
  { name: 'dumbbell', label: 'Dumbbell', tags: ['fitness'] },
  { name: 'graduation-cap', label: 'Graduation' },
  { name: 'briefcase', label: 'Briefcase' },
  { name: 'building-2', label: 'Building' },
  { name: 'store', label: 'Store' },
  { name: 'globe', label: 'Globe' },
  { name: 'wifi', label: 'Wi‑Fi' },
  { name: 'bluetooth', label: 'Bluetooth' },
  { name: 'battery-full', label: 'Battery' },
  { name: 'smartphone', label: 'Smartphone' },
  { name: 'laptop', label: 'Laptop' },
  { name: 'monitor', label: 'Monitor' },
  { name: 'headphones', label: 'Headphones' },
  { name: 'watch', label: 'Watch' },
  { name: 'paw-print', label: 'Paw' },
  { name: 'leaf', label: 'Leaf', tags: ['eco'] },
  { name: 'droplets', label: 'Droplets' },
  { name: 'sun', label: 'Sun' },
  { name: 'moon', label: 'Moon' },
  { name: 'party-popper', label: 'Party' },
  { name: 'cake', label: 'Cake' },
  { name: 'gift', label: 'Gift' },
  { name: 'thumbs-up', label: 'Thumbs up' },
  { name: 'thumbs-down', label: 'Thumbs down' },
  { name: 'trophy', label: 'Trophy' },
  { name: 'medal', label: 'Medal' },
  { name: 'badge-check', label: 'Verified' },
  { name: 'megaphone', label: 'Megaphone' },
  { name: 'handshake', label: 'Handshake' },
  { name: 'heart-handshake', label: 'Charity' },
  { name: 'heart-pulse', label: 'Health' },
  { name: 'pill', label: 'Pill' },
  { name: 'flask-conical', label: 'Science' },
  { name: 'code-2', label: 'Code' },
  { name: 'terminal', label: 'Terminal' },
  { name: 'database', label: 'Database' },
  { name: 'server', label: 'Server' },
  { name: 'shield', label: 'Shield' },
  { name: 'scale', label: 'Scale' },
  { name: 'dollar-sign', label: 'Dollar' },
  { name: 'piggy-bank', label: 'Savings' },
  { name: 'package', label: 'Package' },
  { name: 'truck', label: 'Truck' },
  { name: 'qr-code', label: 'QR code' },
  { name: 'printer', label: 'Printer' },
  { name: 'bookmark', label: 'Bookmark' },
  { name: 'flag', label: 'Flag' },
  { name: 'pin', label: 'Pin' },
  { name: 'filter', label: 'Filter' },
  { name: 'sliders-horizontal', label: 'Sliders' },
  { name: 'layout-grid', label: 'Grid' },
  { name: 'list', label: 'List' },
  { name: 'menu', label: 'Menu' },
  { name: 'ellipsis', label: 'More' },
  { name: 'arrow-right', label: 'Arrow right' },
  { name: 'arrow-left', label: 'Arrow left' },
  { name: 'arrow-up', label: 'Arrow up' },
  { name: 'arrow-down', label: 'Arrow down' },
  { name: 'refresh-cw', label: 'Refresh' },
  { name: 'external-link', label: 'External link' },
  { name: 'maximize', label: 'Maximize' },
  { name: 'zoom-in', label: 'Zoom in' },
  { name: 'zoom-out', label: 'Zoom out' },
  { name: 'layers', label: 'Layers' },
  { name: 'clapperboard', label: 'Clapperboard' },
  { name: 'tv', label: 'TV' },
  { name: 'podcast', label: 'Podcast' },
  { name: 'newspaper', label: 'Newspaper' },
  { name: 'file-text', label: 'Article' },
  { name: 'book-open', label: 'Book' },
  { name: 'smile', label: 'Smile' },
  { name: 'frown', label: 'Frown' },
  { name: 'recycle', label: 'Recycle' },
  { name: 'sun-medium', label: 'Solar' },
];

export const ICON_CATALOG: IconDef[] = [
  ...MATERIAL.map((i) => ({ ...i, set: 'material' as const })),
  ...LUCIDE.map((i) => ({ ...i, set: 'lucide' as const })),
];

const LUCIDE_CDN = 'https://cdn.jsdelivr.net/npm/lucide-static@0.469.0/icons';

export function iconAssetId(set: IconSetId, name: string): string {
  return `icon:${set}:${name}`;
}

export function parseIconAssetId(
  raw: string | null | undefined,
): { set: IconSetId; name: string } | null {
  const s = String(raw || '');
  const m = /^icon:(material|lucide):(.+)$/.exec(s);
  if (!m) return null;
  return { set: m[1] as IconSetId, name: m[2] };
}

export function lucideSvgUrl(name: string): string {
  return `${LUCIDE_CDN}/${encodeURIComponent(name)}.svg`;
}

export function findIconDef(set: IconSetId, name: string): IconDef | undefined {
  return ICON_CATALOG.find((i) => i.set === set && i.name === name);
}

export function filterIcons(
  query: string,
  setFilter: IconSetId | 'all' = 'all',
): IconDef[] {
  const q = query.trim().toLowerCase();
  return ICON_CATALOG.filter((icon) => {
    if (setFilter !== 'all' && icon.set !== setFilter) return false;
    if (!q) return true;
    const hay = [icon.name, icon.label, ...(icon.tags || [])].join(' ').toLowerCase();
    return hay.includes(q) || hay.replace(/[-_]/g, ' ').includes(q);
  });
}
